version: "3.8"

services:
  db:
    container_name: db
    image: docker.io/postgres:15
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stream
    ports:
      - 5432:5432
    volumes:
      - db_data:/data/postgres
volumes:
  db_data:
    driver: local
