version: "3.8"

services:
  db:
    container_name: db
    image: docker.io/postgres:15
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stream
    ports:
      - 5432:5432
    volumes:
      - db_data:/data/postgres
  app:
    container_name: vine_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    command: >
      bash -c "node scripts/make-file/writer.js && cp great-size-file.xlsx public/ && npm start"
    ports:
      - 3333:3333
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  db_data:
    driver: local
